# Generated by Django 4.2.4 on 2023-09-01 15:52

from django.db import migrations, models
import list_item_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_do_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now=True)),
                ('item', models.CharField(max_length=128, validators=[list_item_app.validators.validate_item_and_notes])),
                ('notes', models.TextField(max_length=512, null=True, validators=[list_item_app.validators.validate_item_and_notes])),
            ],
        ),
    ]
