# Generated by Django 4.2.4 on 2023-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_item_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_item',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
